# ExternalName Services for RDS in Staging
# These allow K8s services to connect to RDS using internal service names
# The actual RDS endpoints come from Terraform output
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-user-staging.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-product-staging.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-order-staging.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-inventory-staging.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-payment-staging.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-notification-staging.xxx.rds.amazonaws.com
