# Common Configuration for all services
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: shopflow
  labels:
    app.kubernetes.io/part-of: shopflow-platform
data:
  NODE_ENV: 'production'
  LOG_LEVEL: 'info'
  # Kafka (short name works within same namespace)
  KAFKA_BROKERS: 'kafka:9092'
  # Redis
  REDIS_HOST: 'redis'
  REDIS_PORT: '6379'
  # Elasticsearch
  ELASTICSEARCH_NODE: 'http://elasticsearch:9200'
