# ExternalName Services for RDS in Production
# These allow K8s services to connect to RDS using internal service names
# The actual RDS endpoints come from Terraform output
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-user
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-user-prod.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-product-prod.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-order
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-order-prod.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-inventory
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-inventory-prod.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-payment
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-payment-prod.xxx.rds.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-notification
  namespace: shopflow
spec:
  type: ExternalName
  externalName: shopflow-notification-prod.xxx.rds.amazonaws.com
